
create table person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar NOT NULL UNIQUE ,
    password varchar NOT NULL,
    role varchar NOT NULL
);

create table person_info (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar NOT NULL,
    birth_year int CHECK (birth_year > 1900) NOT NULL,
    email varchar UNIQUE NOT NULL,
    phone varchar CHECK (length(phone) = 12) UNIQUE NOT NULL,
    person_id int UNIQUE REFERENCES person(id) ON DELETE CASCADE
);

create table book (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    author varchar,
    year int,
    person_info_id int REFERENCES person_info(id) ON DELETE SET NULL
);